"""
Consolidated Feature Engineering Pipeline

Replicates the final dataset (v6) generated by the sequential pipeline
(v1 -> v2 -> v3 -> v4 -> v5 -> v6) in a single script.

This script processes `modeling_row_folds.csv` and outputs:
- artifacts/features/features_final_dev.csv
- artifacts/features/features_final_holdout.csv
"""

from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
ROOT = Path(__file__).resolve().parents[2]
SPLITS_DIR = ROOT / "data" / "splits"
NORM_DIR = ROOT / "artifacts" / "data_intake" / "normalized"
FEATURES_DIR = ROOT / "artifacts" / "features"

FEATURES_DIR.mkdir(parents=True, exist_ok=True)

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
PHYSICAL_METRICS = [
    "sprints", "hsr", "distance", "mean_max_speed", "peak_speed",
    "shots", "shots_on_target", "shots_under_press", "shots_top_third",
]

PERIOD_OFFSET = {"half_1": 0.0, "half_2": 45.0, "extra_time_1": 90.0, "extra_time_2": 105.0}
POSITIONS = ["A", "D", "M", "G"]
EPSILON = 1e-6

# ---------------------------------------------------------------------------
# v1 Features
# ---------------------------------------------------------------------------
def engineer_v1_features(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    # Continuous match minute at checkpoint
    out["checkpoint_cont_min"] = (
        out["checkpoint_period"].map(PERIOD_OFFSET).fillna(0).astype(float)
        + out["checkpoint_min"].astype(float)
    )

    # Minutes elapsed since player entered pitch (floor at 1)
    out["elapsed_min"] = (out["checkpoint_cont_min"] - out["minute_in"].astype(float)).clip(lower=1.0)

    # Per physical metric features
    for m in PHYSICAL_METRICS:
        c_col = f"cumul_{m}"
        l_col = f"last15_{m}"
        if c_col not in out.columns or l_col not in out.columns:
            continue

        c = out[c_col].astype(float)
        l = out[l_col].astype(float)

        out[f"ratio_{m}"] = l / (c + EPSILON)
        expected_pace = (c / out["elapsed_min"]) * 15.0
        out[f"pace_delta_{m}"] = l - expected_pace
        out[f"pm_{m}"] = c / out["elapsed_min"]
        out[f"rate15_{m}"] = l / 15.0

    # Position binary indicators
    for pos in POSITIONS:
        out[f"is_pos_{pos}"] = (out["position"] == pos).astype(float)

    # Late-game indicator
    out["is_late_game"] = out["checkpoint"].isin(["H2_30", "H2_45"]).astype(float)

    # Context interactions
    is_home_f = out["is_home"].astype(float)
    out["home_x_last15_sprints"] = is_home_f * out["last15_sprints"].astype(float)
    out["home_x_last15_shots"]   = is_home_f * out["last15_shots"].astype(float)
    out["home_x_rate15_sprints"] = is_home_f * out.get("rate15_sprints", out["last15_sprints"].astype(float) / 15.0)

    out["attacker_x_cumul_shots"]           = out["is_pos_A"] * out["cumul_shots"].astype(float)
    out["attacker_x_cumul_shots_on_target"] = out["is_pos_A"] * out["cumul_shots_on_target"].astype(float)
    out["midfielder_x_cumul_shots"]         = out["is_pos_M"] * out["cumul_shots"].astype(float)

    out["late_x_rate15_sprints"] = out["is_late_game"] * out.get("rate15_sprints", out["last15_sprints"].astype(float) / 15.0)

    return out

# ---------------------------------------------------------------------------
# v2 Features (Events) - Excluding RUN
# ---------------------------------------------------------------------------
def _attach_windows(events: pd.DataFrame, checkpoints: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    ev = events.copy()
    ev["event_cont_min"] = (ev["period"].map(PERIOD_OFFSET).fillna(0).astype(float) + ev["minute"].astype(float))
    cp = checkpoints[["player_appearance_id", "checkpoint", "checkpoint_cont_min"]]
    merged = ev.merge(cp, on="player_appearance_id", how="inner")

    cumul  = merged[merged["event_cont_min"] <= merged["checkpoint_cont_min"]].copy()
    last15 = merged[(merged["event_cont_min"] > merged["checkpoint_cont_min"] - 15.0) &
                    (merged["event_cont_min"] <= merged["checkpoint_cont_min"])].copy()
    return cumul, last15

def _fill_zeros(agg: pd.DataFrame, base: pd.DataFrame, fill_val: float = 0.0) -> pd.DataFrame:
    keys = ["player_appearance_id", "checkpoint"]
    result = base[keys].merge(agg, on=keys, how="left")
    num_cols = result.select_dtypes(include="number").columns.difference(keys)
    result[num_cols] = result[num_cols].fillna(fill_val)
    return result

def _rate(numerator: pd.Series, denominator: pd.Series) -> pd.Series:
    return np.where(denominator > 0, numerator / denominator, 0.0)

def _agg_pass(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    grp = df.groupby(["player_appearance_id", "checkpoint"])
    count      = grp["id"].count().rename(f"{prefix}_count")
    acc_sum    = grp["accurate"].apply(lambda s: s.astype(float).sum())
    top_sum    = grp["stage"].apply(lambda s: (s == "top").sum())
    middle_sum = grp["stage"].apply(lambda s: (s == "middle").sum())

    out = pd.concat([count, acc_sum, top_sum, middle_sum], axis=1)
    out.columns = [f"{prefix}_count", "acc_sum", "top_sum", "middle_sum"]
    out = out.reset_index()

    out[f"{prefix}_accurate_rate"] = _rate(out["acc_sum"], out[f"{prefix}_count"])
    out[f"{prefix}_top_share"]     = _rate(out["top_sum"], out[f"{prefix}_count"])
    out[f"{prefix}_middle_share"]  = _rate(out["middle_sum"], out[f"{prefix}_count"])
    return out.drop(columns=["acc_sum", "top_sum", "middle_sum"])

def _agg_pressure(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    grp = df.groupby(["player_appearance_id", "checkpoint"])
    count     = grp["id"].count().rename(f"{prefix}_count")
    acc_sum   = grp["accurate"].apply(lambda s: s.astype(float).sum())
    turn_sum  = grp["press_induced_outcome"].apply(lambda s: (s == "turnover").sum())
    top_sum   = grp["stage"].apply(lambda s: (s == "top").sum())
    angle_sum = grp["pass_angle"].apply(lambda s: s.notna().sum())

    out = pd.concat([count, acc_sum, turn_sum, top_sum, angle_sum], axis=1)
    out.columns = [f"{prefix}_count", "acc_s", "turn_s", "top_s", "angle_s"]
    out = out.reset_index()

    out[f"{prefix}_accurate_rate"]              = _rate(out["acc_s"], out[f"{prefix}_count"])
    out[f"{prefix}_turnover_rate"]              = _rate(out["turn_s"], out[f"{prefix}_count"])
    out[f"{prefix}_top_share"]                  = _rate(out["top_s"], out[f"{prefix}_count"])
    out[f"{prefix}_pass_angle_observed_share"]  = _rate(out["angle_s"], out[f"{prefix}_count"])
    return out.drop(columns=["acc_s", "turn_s", "top_s", "angle_s"])

def _agg_shot(df: pd.DataFrame, prefix: str) -> pd.DataFrame:
    grp = df.groupby(["player_appearance_id", "checkpoint"])
    count    = grp["id"].count().rename(f"{prefix}_count")
    top_sum  = grp["stage"].apply(lambda s: (s == "top").sum())
    press_sum = grp["under_pressure"].apply(lambda s: s.astype(float).sum())
    reg_sum  = grp["play_pattern"].apply(lambda s: (s == "regular_play").sum())

    out = pd.concat([count, top_sum, press_sum, reg_sum], axis=1)
    out.columns = [f"{prefix}_count", "top_s", "press_s", "reg_s"]
    out = out.reset_index()

    out[f"{prefix}_top_share"]              = _rate(out["top_s"], out[f"{prefix}_count"])
    out[f"{prefix}_under_pressure_rate"]    = _rate(out["press_s"], out[f"{prefix}_count"])
    out[f"{prefix}_regular_play_share"]     = _rate(out["reg_s"], out[f"{prefix}_count"])
    return out.drop(columns=["top_s", "press_s", "reg_s"])

def build_event_features(event_df: pd.DataFrame, checkpoints: pd.DataFrame, agg_fn, prefix: str) -> pd.DataFrame:
    cumul_ev, last15_ev = _attach_windows(event_df, checkpoints)
    keys = ["player_appearance_id", "checkpoint"]
    cumul_agg  = _fill_zeros(_agg_fn_call(agg_fn, cumul_ev, f"cumul_{prefix}"), checkpoints, 0.0)
    last15_agg = _fill_zeros(_agg_fn_call(agg_fn, last15_ev, f"last15_{prefix}"), checkpoints, 0.0)
    return cumul_agg.merge(last15_agg, on=keys, how="outer")

def _agg_fn_call(fn, df, prefix):
    if df.empty:
        return pd.DataFrame(columns=["player_appearance_id", "checkpoint"])
    return fn(df, prefix)

# ---------------------------------------------------------------------------
# v3 Features
# ---------------------------------------------------------------------------
def engineer_v3_features(df: pd.DataFrame) -> pd.DataFrame:
    out = df.copy()

    # 1. Formation Parsing
    splits = out["formation"].astype(str).str.split("-")
    def get_defs(s):
        try: return float(s[0])
        except: return 0.0
    def get_atts(s):
        try: return float(s[-1])
        except: return 0.0
    def get_mids(s):
        try: return sum(float(x) for x in s[1:-1])
        except: return 0.0

    out["formation_defenders"] = splits.apply(get_defs)
    out["formation_attackers"] = splits.apply(get_atts)
    out["formation_midfielders"] = splits.apply(get_mids)
    out["is_lone_striker_system"] = (out["formation_attackers"] == 1).astype(float)
    out["is_back_three"] = (out["formation_defenders"].isin([3, 5])).astype(float)
    
    # 2. Formation Interactions
    out["attacker_in_lone_system"] = out.get("is_pos_A", 0) * out["is_lone_striker_system"]
    out["defender_in_back_three"] = out.get("is_pos_D", 0) * out["is_back_three"]
    
    total_outfield = out["formation_defenders"] + out["formation_midfielders"] + out["formation_attackers"]
    out["attacker_ratio"] = out["formation_attackers"] / total_outfield.replace(0, 10.0)

    # 3. Fresh legs / substitute features
    out["is_substitute"] = (out["minute_in"] > 1).astype(float)
    out["fresh_legs_advantage"] = out.get("elapsed_min", 0) / out["checkpoint_cont_min"].replace(0, 1.0)
    out["sub_x_sprints"] = out["is_substitute"] * out.get("last15_sprints", 0).astype(float)

    # 4. High-value combinations
    out["high_threat_sprints"] = out.get("last15_sprints", 0).astype(float) * out.get("last15_shots_top_third", 0).astype(float)
    out["effective_presser"] = out.get("last15_pressure_count", 0).astype(float) * out.get("last15_pressure_turnover_rate", 0).astype(float)

    # 5. Team-level metrics
    team_grp = out.groupby(["fixture_id", "checkpoint", "is_home"])
    out["team_cumul_shots"] = team_grp["cumul_shots"].transform("sum")
    out["player_shot_share"] = out["cumul_shots"].astype(float) / out["team_cumul_shots"].replace(0, 1.0)
    out["team_last15_momentum_sprints"] = team_grp["last15_sprints"].transform("sum")
    out["team_last15_momentum_shots"] = team_grp["last15_shots"].transform("sum")

    return out

# ---------------------------------------------------------------------------
# v4 Features
# ---------------------------------------------------------------------------
def add_xg_features(df, shots_df, is_train=True, rf_model=None):
    s = shots_df.copy()
    s["up"] = s["under_pressure"].astype(int)
    
    if is_train:
        scorers = df[df["scored_after"] == 1]["player_appearance_id"].unique()
        s["is_scorer"] = s["player_appearance_id"].isin(scorers).astype(int)
        rf_model = RandomForestClassifier(n_estimators=50, random_state=42)
        X_xg = pd.get_dummies(s[["stage", "body_part", "technique", "play_pattern", "up"]])
        rf_model.fit(X_xg, s["is_scorer"])
        rf_model.feature_names_ = X_xg.columns
    
    X_xg = pd.get_dummies(s[["stage", "body_part", "technique", "play_pattern", "up"]])
    for col in rf_model.feature_names_:
        if col not in X_xg.columns:
            X_xg[col] = 0
    X_xg = X_xg[rf_model.feature_names_]
    
    s["t"] = rf_model.predict_proba(X_xg)[:, 1]
    s["min"] = s["period"].map(PERIOD_OFFSET) + s["minute"]
    
    merged_xg = s.merge(df[["player_appearance_id", "checkpoint", "checkpoint_cont_min"]], on="player_appearance_id")
    c_xg = merged_xg[merged_xg["min"] <= merged_xg["checkpoint_cont_min"]].groupby(["player_appearance_id", "checkpoint"])["t"].sum().rename("cumul_threat")
    l_xg = merged_xg[(merged_xg["min"] > merged_xg["checkpoint_cont_min"]-15) & (merged_xg["min"] <= merged_xg["checkpoint_cont_min"])].groupby(["player_appearance_id", "checkpoint"])["t"].sum().rename("last15_threat")
    
    out = df.merge(c_xg, on=["player_appearance_id", "checkpoint"], how="left")
    out = out.merge(l_xg, on=["player_appearance_id", "checkpoint"], how="left")
    out[["cumul_threat", "last15_threat"]] = out[["cumul_threat", "last15_threat"]].fillna(0)
    return out, rf_model

def add_centrality_features(df, passes_df):
    acc_p = passes_df[passes_df["accurate"]==True].copy()
    acc_p["min"] = acc_p["period"].map(PERIOD_OFFSET) + acc_p["minute"]
    
    c_made_merge = acc_p.merge(df[["player_appearance_id", "checkpoint", "checkpoint_cont_min"]], on="player_appearance_id")
    c_made = c_made_merge[c_made_merge["min"] <= c_made_merge["checkpoint_cont_min"]].groupby(["player_appearance_id", "checkpoint"]).size().rename("cumul_passes_made")
    l_made = c_made_merge[(c_made_merge["min"] > c_made_merge["checkpoint_cont_min"]-15) & (c_made_merge["min"] <= c_made_merge["checkpoint_cont_min"])].groupby(["player_appearance_id", "checkpoint"]).size().rename("last15_passes_made")
    
    rec_p = acc_p[acc_p["addressee_player_appearance_id"].notna()]
    c_rec_merge = rec_p.merge(df[["player_appearance_id", "checkpoint", "checkpoint_cont_min"]], left_on="addressee_player_appearance_id", right_on="player_appearance_id")
    c_rec = c_rec_merge[c_rec_merge["min"] <= c_rec_merge["checkpoint_cont_min"]].groupby(["player_appearance_id_y", "checkpoint"]).size().rename("cumul_passes_received")
    c_rec.index.names = ["player_appearance_id", "checkpoint"]
    
    l_rec = c_rec_merge[(c_rec_merge["min"] > c_rec_merge["checkpoint_cont_min"]-15) & (c_rec_merge["min"] <= c_rec_merge["checkpoint_cont_min"])].groupby(["player_appearance_id_y", "checkpoint"]).size().rename("last15_passes_received")
    l_rec.index.names = ["player_appearance_id", "checkpoint"]
    
    out = df.merge(c_made, on=["player_appearance_id", "checkpoint"], how="left")
    out = out.merge(l_made, on=["player_appearance_id", "checkpoint"], how="left")
    out = out.merge(c_rec, on=["player_appearance_id", "checkpoint"], how="left")
    out = out.merge(l_rec, on=["player_appearance_id", "checkpoint"], how="left")
    
    new_cols = ["cumul_passes_made", "last15_passes_made", "cumul_passes_received", "last15_passes_received"]
    out[new_cols] = out[new_cols].fillna(0)
    
    out["cumul_in_out_ratio"] = out["cumul_passes_received"] / out["cumul_passes_made"].replace(0, 1.0)
    out["last15_in_out_ratio"] = out["last15_passes_received"] / out["last15_passes_made"].replace(0, 1.0)
    return out

# ---------------------------------------------------------------------------
# Main Routine
# ---------------------------------------------------------------------------
def run():
    print("Loading base table...")
    df = pd.read_csv(SPLITS_DIR / "modeling_row_folds.csv")
    
    print("Engineering v1 features...")
    df = engineer_v1_features(df)
    
    dev_df  = df[df["partition_role"] == "development"].copy()
    hold_df = df[df["partition_role"] == "holdout"].copy()
    
    print("Loading event tables...")
    pass_ev  = pd.read_csv(NORM_DIR / "player_appearance_pass_normalized.csv")
    press_ev = pd.read_csv(NORM_DIR / "player_appearance_behaviour_under_pressure_normalized.csv")
    shot_ev  = pd.read_csv(NORM_DIR / "player_appearance_shot_limited_normalized.csv")
    shot_ev = shot_ev[shot_ev["own_goal_player_appearance_id"].isna()].copy()
    
    event_specs = [
        ("pass",     pass_ev,  _agg_pass),
        ("pressure", press_ev, _agg_pressure),
        ("shot",     shot_ev,  _agg_shot),
        # NOTE: "run" is excluded per v6 spec.
    ]
    
    cp_dev  = dev_df[["player_appearance_id", "checkpoint", "checkpoint_cont_min"]]
    cp_hold = hold_df[["player_appearance_id", "checkpoint", "checkpoint_cont_min"]]
    
    keys = ["player_appearance_id", "checkpoint"]
    
    print("Engineering v2 features...")
    for family, ev_data, agg_fn in event_specs:
        print(f"  -> Aggregating {family}...")
        feat_dev = build_event_features(ev_data, cp_dev, agg_fn, family)
        feat_hold = build_event_features(ev_data, cp_hold, agg_fn, family)
        dev_df = dev_df.merge(feat_dev, on=keys, how="left")
        hold_df = hold_df.merge(feat_hold, on=keys, how="left")
        
    print("Engineering v3 features...")
    dev_df = engineer_v3_features(dev_df)
    hold_df = engineer_v3_features(hold_df)
    
    print("Engineering v4 features...")
    dev_df, rf_model = add_xg_features(dev_df, shot_ev, is_train=True)
    hold_df, _ = add_xg_features(hold_df, shot_ev, is_train=False, rf_model=rf_model)
    dev_df = add_centrality_features(dev_df, pass_ev)
    hold_df = add_centrality_features(hold_df, pass_ev)
    
    print("Engineering v5 features (exposure)...")
    dev_df["exposure"] = (dev_df["minute_out"] - dev_df["checkpoint_cont_min"]).clip(lower=1)
    hold_df["exposure"] = (hold_df["minute_out"] - hold_df["checkpoint_cont_min"]).clip(lower=1)
    
    print(f"Saving final datasets (v6 final) (shape dev: {dev_df.shape}, holdout: {hold_df.shape})...")
    dev_df.to_csv(FEATURES_DIR / "features_final_dev.csv", index=False)
    hold_df.to_csv(FEATURES_DIR / "features_final_holdout.csv", index=False)
    
    # Update WHAT_HAS_BEEN_DONE.md per user rules
    with open("WHAT_HAS_BEEN_DONE.md", "a") as f:
        f.write("\n- Created `src/python/feature_engineering_consolidated.py` to consolidate feature engineering versions v1 through v6 into a single execution step.\n")
        
    print("Done.")

if __name__ == "__main__":
    run()
