"""
Step 13c: Model Tuning Report Generation

Reads outputs from tune_lr.py and tune_xgb.py,
writes artifacts/tuning/best_params.json, artifacts/tuning/finalist_summary.csv
and docs/model_tuning.md.
"""

from __future__ import annotations

import json
from pathlib import Path
import pandas as pd

ROOT       = Path(__file__).resolve().parents[2]
TUNING_DIR = ROOT / "artifacts" / "tuning"
DOCS_DIR   = ROOT / "docs"

def run() -> None:
    # Load LR outputs
    with open(TUNING_DIR / "best_params_lr.json", "r") as f:
        best_lr = json.load(f)
    lr_trials = pd.read_csv(TUNING_DIR / "lr_trials.csv")
    
    # Load XGB outputs
    with open(TUNING_DIR / "best_params_xgb.json", "r") as f:
        best_xgb = json.load(f)
    xgb_trials = pd.read_csv(TUNING_DIR / "xgb_trials.csv")

    # Combine best_params
    best_params = {
        "LogisticRegression": best_lr,
        "XGBoost": best_xgb,
    }
    (TUNING_DIR / "best_params.json").write_text(
        json.dumps(best_params, indent=2), encoding="utf-8"
    )

    # Finalist summary
    finalist_rows = []
    
    # LR row
    lr_best_trial_idx = lr_trials["mean_pr_auc"].idxmax()
    lr_row = {"model": "LogisticRegression"}
    lr_row["best_trial"] = lr_trials.loc[lr_best_trial_idx, "trial"]
    for k, v in best_lr["params"].items():
        lr_row[k] = v
    lr_row["mean_pr_auc"] = best_lr["mean_pr_auc"]
    for k, v in best_lr.items():
        if k not in ["params", "mean_pr_auc"]:
            lr_row[k] = v
    finalist_rows.append(lr_row)
    
    # XGB row
    xgb_best_trial_idx = xgb_trials["mean_pr_auc"].idxmax()
    xgb_row = {"model": "XGBoost"}
    xgb_row["best_trial"] = xgb_trials.loc[xgb_best_trial_idx, "trial"]
    for k, v in best_xgb["params"].items():
        xgb_row[k] = v
    xgb_row["mean_pr_auc"] = best_xgb["mean_pr_auc"]
    for k, v in best_xgb.items():
        if k not in ["params", "mean_pr_auc"]:
            xgb_row[k] = v
    finalist_rows.append(xgb_row)
    
    finalist_df = pd.DataFrame(finalist_rows)
    finalist_df.to_csv(TUNING_DIR / "finalist_summary.csv", index=False)

    # Write Report
    _write_report(lr_trials, xgb_trials, best_params)
    print("Done. Outputs in artifacts/tuning/ and docs/model_tuning.md")


def _write_report(lr_trials: pd.DataFrame, xgb_trials: pd.DataFrame, best_params: dict) -> None:
    lines: list[str] = []
    a = lines.append

    a("# Model Tuning Report — Step 13")
    a("")
    a("Generated by `src/python/model_tuning_report.py` (Step 13 of `docs/plan.md`).")
    a("")
    a("Primary selection metric: **mean CV PR AUC** (per user request).")
    a("Feature set: **v2** (85 v1 features + 38 event-table features).")
    a("")

    a("## 1. Candidate Models and Search Spaces")
    a("")
    a("| Model | Tuned Parameters | Fixed Parameters |")
    a("|---|---|---|")
    a("| LogisticRegression | C ∈ [1e-3, 100] (log), penalty/solver ∈ {l2_lbfgs, l2_saga, l1_saga} | class_weight=balanced, max_iter=2000 |")
    a("| XGBoost | n_estimators, max_depth, learning_rate, min_child_weight, subsample, colsample_bytree, reg_alpha, reg_lambda | scale_pos_weight (fold-computed), eval_metric=logloss |")
    a("")

    a("## 2. Best Hyperparameters")
    a("")
    for model_name in ["LogisticRegression", "XGBoost"]:
        bp = best_params[model_name]
        a(f"### {model_name}")
        a("")
        a(f"Best trial PR AUC: **{bp['mean_pr_auc']:.4f}**")
        a("")
        a("| Parameter | Value |")
        a("|---|---|")
        for k, v in bp["params"].items():
            val_str = f"{v:.6g}" if isinstance(v, float) else str(v)
            a(f"| {k} | {val_str} |")
        a("")

    a("## 3. Performance Summary")
    a("")
    a("| Model | Trials | Best PR AUC | Best Bal. Acc. | Best ROC AUC | Best Brier |")
    a("|---|---:|---:|---:|---:|---:|---:|")
    for model_name, trials_df in [
        ("LogisticRegression", lr_trials),
        ("XGBoost",            xgb_trials),
    ]:
        bp = best_params[model_name]
        a(f"| {model_name} | {len(trials_df)} | {bp['mean_pr_auc']:.4f}"
          f" | {bp.get('mean_balanced_accuracy', float('nan')):.4f}"
          f" | {bp.get('mean_roc_auc', float('nan')):.4f}"
          f" | {bp.get('mean_pr_auc', float('nan')):.4f}"
          f" | {bp.get('mean_brier_score', float('nan')):.4f} |")
    a("")

    a("## 4. Model Selection Decision")
    a("")
    lr_pr  = best_params["LogisticRegression"]["mean_pr_auc"]
    xgb_pr = best_params["XGBoost"]["mean_pr_auc"]
    winner = "LogisticRegression" if lr_pr >= xgb_pr else "XGBoost"
    a(f"Primary metric (PR AUC): LR = {lr_pr:.4f}, XGBoost = {xgb_pr:.4f}.")
    a(f"**Selected finalist: {winner}** (higher mean PR AUC).")
    a("")
    a("Both models are retained as finalists for the RQ ablation matrix (Step 15). "
      "Final selection after holdout evaluation (Step 17).")
    a("")
    a("## 5. Next Steps (Step 14)")
    a("Calibrate probabilities on OOF predictions using Platt scaling and isotonic regression. "
      "Select operating threshold using development data only.")

    (DOCS_DIR / "model_tuning.md").write_text("\n".join(lines), encoding="utf-8")

if __name__ == "__main__":
    run()
