from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd

from data_intake import NA_TOKENS, normalize_dataframe, project_root


BASE_DATASET = "players_quarters_final.csv"
EVENT_DATASETS = [
    "player_appearance_pass.csv",
    "player_appearance_behaviour_under_pressure.csv",
    "player_appearance_run.csv",
    "player_appearance_shot_limited.csv",
]


def load_normalized_csv(path: Path) -> pd.DataFrame:
    raw = pd.read_csv(path, keep_default_na=True, na_values=NA_TOKENS, low_memory=False)
    return normalize_dataframe(raw)


def canonical_modeling_ids(data_dir: Path) -> set[int]:
    base_df = load_normalized_csv(data_dir / BASE_DATASET)
    ids = pd.to_numeric(base_df["player_appearance_id"], errors="coerce").dropna()
    return set(ids.astype("Int64").astype(int).tolist())


def build_scope_artifacts() -> None:
    root = project_root()
    data_dir = root / "data"

    out_dir = root / "artifacts" / "modeling_scope"
    modeling_dir = out_dir / "modeling_subsets"
    reference_dir = out_dir / "out_of_scope_reference"

    out_dir.mkdir(parents=True, exist_ok=True)
    modeling_dir.mkdir(parents=True, exist_ok=True)
    reference_dir.mkdir(parents=True, exist_ok=True)

    canonical_ids = canonical_modeling_ids(data_dir)

    summary_rows: list[dict[str, Any]] = []

    for filename in EVENT_DATASETS:
        dataset_name = Path(filename).stem
        df = load_normalized_csv(data_dir / filename)

        if "player_appearance_id" not in df.columns:
            raise ValueError(f"Dataset {dataset_name} is missing player_appearance_id required for scope filtering.")

        ids = pd.to_numeric(df["player_appearance_id"], errors="coerce").astype("Int64")
        in_scope_mask = ids.isin(canonical_ids)

        in_scope_df = df[in_scope_mask].copy()
        out_scope_df = df[~in_scope_mask].copy()

        in_scope_df.to_csv(modeling_dir / f"{dataset_name}_modeling_scope.csv", index=False)
        out_scope_df.to_csv(reference_dir / f"{dataset_name}_out_of_scope.csv", index=False)

        unique_ids_total = int(ids.dropna().nunique())
        unique_ids_in_scope = int(pd.to_numeric(in_scope_df["player_appearance_id"], errors="coerce").dropna().nunique())
        unique_ids_out_scope = int(pd.to_numeric(out_scope_df["player_appearance_id"], errors="coerce").dropna().nunique())

        kept_rows = int(len(in_scope_df))
        dropped_rows = int(len(out_scope_df))
        total_rows = int(len(df))
        dropped_pct = 0.0 if total_rows == 0 else (dropped_rows / total_rows) * 100.0

        summary_rows.append(
            {
                "dataset": dataset_name,
                "total_rows": total_rows,
                "kept_rows": kept_rows,
                "dropped_rows": dropped_rows,
                "dropped_pct": round(dropped_pct, 4),
                "unique_player_appearance_ids_total": unique_ids_total,
                "unique_player_appearance_ids_kept": unique_ids_in_scope,
                "unique_player_appearance_ids_dropped": unique_ids_out_scope,
            }
        )

    summary_df = pd.DataFrame(summary_rows).sort_values("dataset").reset_index(drop=True)
    summary_df.to_csv(out_dir / "scope_summary.csv", index=False)

    write_scope_report(out_dir / "scope_report.md", summary_df, canonical_ids)


def write_scope_report(path: Path, summary_df: pd.DataFrame, canonical_ids: set[int]) -> None:
    lines: list[str] = []
    lines.append("# Modeling Scope Report")
    lines.append("")
    lines.append("This report was generated by `src/python/modeling_scope.py`.")
    lines.append("")
    lines.append("## Policy")
    lines.append("")
    lines.append("- Canonical modeling IDs are taken from `players_quarters_final.player_appearance_id`.")
    lines.append("- For checkpoint modeling, event-table rows are kept only when `player_appearance_id` is in the canonical set.")
    lines.append("- Out-of-scope rows are preserved in separate reference files and excluded from supervised feature generation.")
    lines.append("")
    lines.append("## Canonical Set")
    lines.append("")
    lines.append(f"- Canonical player_appearance_id count: {len(canonical_ids)}")
    lines.append("")
    lines.append("## Kept vs Dropped by Event Dataset")
    lines.append("")
    lines.append("| Dataset | Total rows | Kept rows | Dropped rows | Dropped % | Unique IDs total | Unique IDs kept | Unique IDs dropped |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")

    for _, row in summary_df.iterrows():
        lines.append(
            "| "
            + f"{row['dataset']} | {int(row['total_rows'])} | {int(row['kept_rows'])} | {int(row['dropped_rows'])} | "
            + f"{float(row['dropped_pct']):.4f} | {int(row['unique_player_appearance_ids_total'])} | "
            + f"{int(row['unique_player_appearance_ids_kept'])} | {int(row['unique_player_appearance_ids_dropped'])} |"
        )

    lines.append("")
    lines.append("## Output Files")
    lines.append("")
    lines.append("- `artifacts/modeling_scope/scope_summary.csv`")
    lines.append("- `artifacts/modeling_scope/modeling_subsets/*_modeling_scope.csv`")
    lines.append("- `artifacts/modeling_scope/out_of_scope_reference/*_out_of_scope.csv`")

    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    build_scope_artifacts()
